[project]
name = "medicareguide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.13.2",
    "faster-whisper>=1.0.3",
    "fastembed>=0.4.2",
    "kokoro-onnx>=0.2.1",
    "onnxruntime>=1.20.1",
    "pandas>=3.0.3",
    "pypdf>=6.11.0",
    "requests>=2.34.0",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1",
    "streamlit>=1.35",
    "watchdog>=6.0.0",
    "zipcodes>=1.3.0",
]
